device: "cpu"
seed: 1525
save_dir_path: "saved_models"
epochs_to_save_after: 10

problem_settings:
  reactions:
    train_filename: "whole_sanitized_us_patents.csv"
    val_filename: null
    fp_method: "difference"
    no_agents: True

    n_bits: 2048
    fp_type: "TopologicalTorsion"
    include_agents: False
    agent_weight: 1
    non_agent_weight: 10

    bit_ratio_agents: 0.2

optimization:
  lr: 0.002

training:
  perplexity: 30
  n_epochs: 10
  early_exaggeration: 0
  early_exaggeration_constant: 5
  batch_size: 7000
  bin_search_max_iter: 100
  bin_search_tol: 0.0001
  dist_func_name: "euc"
  min_allowed_sig_sq: 0
  max_allowed_sig_sq: 10000

